
title: Tutoriais
url: "https://contadoria.github.io/Tutoriais"
baseurl: "/Tutoriais"

permalink: /:categories/:title/

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:
  category:
    output: true
    permalink: /categoria/:name/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      type: category
    values:
      layout: "category"
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video